# Generated by Django 5.0.1 on 2024-03-24 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('customer_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.playground')),
            ],
        ),
    ]
