# Generated by Django 5.0.1 on 2024-03-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_playgrounddetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=350, max_digits=6),
            preserve_default=False,
        ),
    ]
