# Generated by Django 5.0.1 on 2024-03-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='playground_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.playgrounddetail'),
            preserve_default=False,
        ),
    ]
