# Generated by Django 5.0.1 on 2024-03-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_hours_alter_customer_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
