# Generated by Django 5.0.1 on 2024-04-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_playground_user_user_playground_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playgrounddetail',
            name='user',
        ),
    ]
