# Generated by Django 5.0.1 on 2024-04-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_user_is_permission_given_alter_playgrounddetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_permission_given',
            field=models.BooleanField(blank=True),
        ),
    ]
