# Generated by Django 5.0.1 on 2024-04-03 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_user_is_owner_alter_user_is_permission_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgrounddetail',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 4)),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_permission_given',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
