# Generated by Django 5.0.1 on 2024-04-11 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0015_customer_bank_customer_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playgrounddetail",
            name="date",
            field=models.DateField(default=datetime.date(2024, 4, 12)),
        ),
    ]
