# Generated by Django 5.0.1 on 2024-04-27 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_playgrounddetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgrounddetail',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 27)),
        ),
    ]
