# Generated by Django 5.0.1 on 2024-04-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_alter_playgrounddetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
