# Generated by Django 5.0.1 on 2024-09-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_alter_customer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgrounddetail',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=8),
        ),
    ]
